site_name: RStoreModule
site_url: https://r0bl0x10501050.github.io/RStoreModule
repo_name: R0bl0x10501050/RStoreModule
repo_url: https://github.com/R0bl0x10501050/RStoreModule

theme:
  name: material
  palette:
  
  # Light mode
    - light blue: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Turn Off The Lights

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Turn On The Lights

nav:
  - Home: index.md
  - Docs: docs.md
  - Quickstart:
    - Installation: Quickstart/installation.md
    - Basic Usage: Quickstart/basic_usage.md
    
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
